/*
 * geniusreferrals_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package campaigns_pkg


/*
 * Interface for the CAMPAIGNS_IMPL
 */
type CAMPAIGNS interface {
    GetCampaign (string, string) (interface{}, error)

    GetCampaigns (string, *int64, *int64, *string, *string) (interface{}, error)
}

/*
 * Factory for the CAMPAIGNS interaface returning CAMPAIGNS_IMPL
 */
func NewCAMPAIGNS() CAMPAIGNS {
    return &CAMPAIGNS_IMPL{}
}