/*
 * geniusreferrals_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package geniusreferrals_lib

/** The base Uri for API calls */
const BASEURI string = "https://api.geniusreferrals.com"

var Config struct {
    /** The content type */
    /** Replace the value of ContentType with an appropriate value */
    ContentType string
    /** Your API Token, you can get your token here https://www.geniusreferrals.com/en/settings/api-access */
    /** Replace the value of XAuthToken with an appropriate value */
    XAuthToken string
}
