/*
 * geniusreferrals_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package authentications_pkg


/*
 * Interface for the AUTHENTICATIONS_IMPL
 */
type AUTHENTICATIONS interface {
    GetAuthentication () (interface{}, error)
}

/*
 * Factory for the AUTHENTICATIONS interaface returning AUTHENTICATIONS_IMPL
 */
func NewAUTHENTICATIONS() AUTHENTICATIONS {
    return &AUTHENTICATIONS_IMPL{}
}