/*
 * geniusreferrals_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/17/2017
 */

package advocates_pkg

import "geniusreferrals_lib/models_pkg"

/*
 * Interface for the ADVOCATES_IMPL
 */
type ADVOCATES interface {
    DeleteAdvocate (string, string) (error)

    PutAdvocate (string, string, *models_pkg.AdvocateForm) (error)

    PostAdvocate (string, *models_pkg.AdvocateForm) (interface{}, error)

    GetAdvocate (string, string) (interface{}, error)

    DeleteAdvocates (string) (error)

    GetAdvocates (string, *int64, *int64, *string, *string) (interface{}, error)

    PatchAdvocate (string, string, []*models_pkg.AdvocatePatchForm) (interface{}, error)
}

/*
 * Factory for the ADVOCATES interaface returning ADVOCATES_IMPL
 */
func NewADVOCATES() ADVOCATES {
    return &ADVOCATES_IMPL{}
}