/*
 * geniusreferrals_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package advocates_pkg

import "geniusreferrals_lib/models_pkg"

/*
 * Interface for the ADVOCATES_IMPL
 */
type ADVOCATES interface {
    DeleteAdvocate (string, string) (error)

    PutAdvocate (string, string, *models_pkg.AdvocateForm) (error)

    PostAdvocate (string, *models_pkg.AdvocateForm) (interface{}, error)

    GetAdvocate (string, string) (interface{}, error)

    DeleteAdvocates (string) (error)

    GetAdvocates (string, *int64, *int64, *string, *string) (interface{}, error)

    PatchAdvocate (string, string, []*models_pkg.AdvocatePatchForm) (interface{}, error)

    GetShareLinks (string, string) (interface{}, error)

    PutPaymentMethod (string, string, int64, *models_pkg.PaymentMethodForm) (error)

    GetPaymentMethod (string, string, int64) (interface{}, error)

    PostPaymentMethod (string, string, *models_pkg.PaymentMethodForm) (interface{}, error)

    GetBonusRedemptionMethod (string) (interface{}, error)

    GetBonusRedemptionMethods () (interface{}, error)

    GetCurrencies () (interface{}, error)

    GetCurrency (string) (interface{}, error)

    GetPaymentMethods (string, string, *int64, *int64, *string, *string) (interface{}, error)
}

/*
 * Factory for the ADVOCATES interaface returning ADVOCATES_IMPL
 */
func NewADVOCATES() ADVOCATES {
    return &ADVOCATES_IMPL{}
}