/*
 * geniusreferrals_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package referrals_pkg

import "geniusreferrals_lib/models_pkg"

/*
 * Interface for the REFERRALS_IMPL
 */
type REFERRALS interface {
    GetReferralOrigin (string) (interface{}, error)

    GetReferralOrigins () (interface{}, error)

    GetReferral (string, string, string) (interface{}, error)

    DeleteReferral (string, string, string) (error)

    PostReferral (string, string, *models_pkg.ReferralForm) (interface{}, error)

    PutReferral (string, string, string, *models_pkg.ReferralForm) (error)

    GetReferrals (string, string, *int64, *int64, *string, *string) (interface{}, error)
}

/*
 * Factory for the REFERRALS interaface returning REFERRALS_IMPL
 */
func NewREFERRALS() REFERRALS {
    return &REFERRALS_IMPL{}
}