/*
 * geniusreferrals_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package bonuses_pkg

import "geniusreferrals_lib/models_pkg"

/*
 * Interface for the BONUSES_IMPL
 */
type BONUSES interface {
    GetBonuses (string, *int64, *int64, *string, *string) (interface{}, error)

    PostBonus (string, *models_pkg.BonusesForm) (interface{}, error)

    GetBonusCheckup (string, string, string, float64) ([]byte, error)

    PostForceBonus (string, *models_pkg.ForceBonusesForm) (interface{}, error)

    GetBonusTrace (string, int64) (interface{}, error)

    DeleteBonus (string, int64) (error)

    GetBonus (string, int64) (interface{}, error)

    GetBonusTraces (string, *int64, *int64, *string, *string) (interface{}, error)
}

/*
 * Factory for the BONUSES interaface returning BONUSES_IMPL
 */
func NewBONUSES() BONUSES {
    return &BONUSES_IMPL{}
}