/*
 * geniusreferrals_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 02/18/2017
 */

package redemptionrequests_pkg

import "geniusreferrals_lib/models_pkg"

/*
 * Interface for the REDEMPTIONREQUESTS_IMPL
 */
type REDEMPTIONREQUESTS interface {
    GetRedemptionRequestStatus (string) (interface{}, error)

    GetRedemptionRequestStatuses () (interface{}, error)

    GetRedemptionRequestAction (string) (interface{}, error)

    GetRedemptionRequestActions () (interface{}, error)

    PatchRedemptionRequest (string, int64) (error)

    PostRedemptionRequest (string, *models_pkg.RedemptionRequestForm) (interface{}, error)

    GetRedemptionRequest (string, string) (interface{}, error)

    GetRedemptionRequests (string, *int64, *int64, *string, *string) (interface{}, error)
}

/*
 * Factory for the REDEMPTIONREQUESTS interaface returning REDEMPTIONREQUESTS_IMPL
 */
func NewREDEMPTIONREQUESTS() REDEMPTIONREQUESTS {
    return &REDEMPTIONREQUESTS_IMPL{}
}